---
title: "NBA Contracts Project"
author: "Brian Papiernik"
date: "2023-11-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 

```{r}
devtools::install_github("abresler/nbastatR")

```

```{r}
library(nbastatR)
```

```{r}
# install.packages("randomForest")
# install.packages("rpart")
# install.packages("caret")
library(randomForest) # Load randomForest package to run bagging
library(rpart) # Load rpart for decision trees
library(caret) # Used for analysing results
#install.packages("splitstackshape")
library(splitstackshape) # Used for stratified sampling
#install.packages("xgboost")
#install.packages("caret")
#install.packages("ggplot2")
#library(devtools) 
#install.packages("githubinstall")
library(devtools)
#install_github("AppliedDataSciencePartners/xgboostExplainer")
#install.packages("SHAPforxgboost")
#install.packages("GGally")
#install.packages("gh")

library(xgboost) # Load XGBoost
library(caret) # Load Caret
library(ggplot2) # Load ggplot2
library(pROC) # Load proc
library(SHAPforxgboost) # Load shap for XGBoost
library(caTools)
library(dplyr)
library(GGally)
library(ggplot2) # Load ggplot2
library(pROC) # Load proc
library(data.table)
library(gh)
library(commonmark)
library(xgboostExplainer)
library(dplyr)
```


```{r}
raptor_stats <- read.csv("2023RaptorPlayer.csv")
contract_stats <- read.csv("NBAcontracts.csv")
histraptor_stats <- read.csv("NBAhistcontracts.csv")
contract_stats2023 <- read.csv("playercontracts2023.csv")
contract_stats2022 <- read.csv("playercontracts2022.csv")
```

```{r}
raptor_stats2022 <- histraptor_stats %>%
  filter(season == 2022)

raptor_stats2021 <- histraptor_stats %>%
  filter(season == 2021)
```



```{r}
# Example: Get year over year data for all players for the 2019 Regular Season
Sys.setenv(VROOM_CONNECTION_SIZE = 262144)  # Adjust the value as needed


# Example: Get defense statistics for all players in the 2018 Regular Season
result <- teams_players_stats(
  seasons = 2023,
  types = "player",
  tables = c("defense","general"),
  season_types = "Regular Season",
  measures = c("Base"),
  modes = "PerGame",
  defenses = "Overall",
  is_plus_minus = FALSE,
  is_pace_adjusted = FALSE,
  periods = 0,
  is_rank = FALSE,
  game_segments = NA,
  divisions_against = NA,
  conferences_against = NA,
  date_from = NA,
  date_to = NA,
  last_n_games = 0,
  locations = NA,
  months = 0,
  season_segments = NA,
  opponents = NA,
  countries = NA,
  weights = NA,
  outcomes = NA,
  playoff_rounds = 0,
  players_experience = NA,
  players_positions = NA,
  colleges = NA,
  draft_picks = NA,
  draft_years = NA,
  game_scopes = NA,
  heights = NA,
  shot_clock_ranges = NA,
  clutch_times = NA,
  ahead_or_behind = "Ahead or Behind",
  general_ranges = "Overall",
  dribble_ranges = "0 Dribbles",
  shot_distance_ranges = "By Zone",
  touch_time_ranges = NA,
  closest_defender_ranges = NA,
  point_diffs = NA,
  starters_bench = NA,
  assign_to_environment = TRUE,
  add_mode_names = TRUE,
  return_message = TRUE
)

# Print the result
print(result)


# Print the result for all players
print(result$dataTable)

```


```{r}
trad_stats <- dataGeneralPlayers
```

```{r}
def_stats <- dataDefensePlayers
```

```{r}
# Example: Get year over year data for all players for the 2019 Regular Season
Sys.setenv(VROOM_CONNECTION_SIZE = 262144)  # Adjust the value as needed


# Example: Get defense statistics for all players in the 2018 Regular Season
result2022 <- teams_players_stats(
  seasons = 2022,
  types = "player",
  tables = c("defense","general"),
  season_types = "Regular Season",
  measures = c("Base"),
  modes = "PerGame",
  defenses = "Overall",
  is_plus_minus = FALSE,
  is_pace_adjusted = FALSE,
  periods = 0,
  is_rank = FALSE,
  game_segments = NA,
  divisions_against = NA,
  conferences_against = NA,
  date_from = NA,
  date_to = NA,
  last_n_games = 0,
  locations = NA,
  months = 0,
  season_segments = NA,
  opponents = NA,
  countries = NA,
  weights = NA,
  outcomes = NA,
  playoff_rounds = 0,
  players_experience = NA,
  players_positions = NA,
  colleges = NA,
  draft_picks = NA,
  draft_years = NA,
  game_scopes = NA,
  heights = NA,
  shot_clock_ranges = NA,
  clutch_times = NA,
  ahead_or_behind = "Ahead or Behind",
  general_ranges = "Overall",
  dribble_ranges = "0 Dribbles",
  shot_distance_ranges = "By Zone",
  touch_time_ranges = NA,
  closest_defender_ranges = NA,
  point_diffs = NA,
  starters_bench = NA,
  assign_to_environment = TRUE,
  add_mode_names = TRUE,
  return_message = TRUE
)

# Print the result
print(result2022)


# Print the result for all players
print(result2022$dataTable)

```

```{r}
trad_stats2022 <- dataGeneralPlayers
```


```{r}
def_stats2022 <- dataDefensePlayers
```

```{r}
# Example: Get year over year data for all players for the 2019 Regular Season
Sys.setenv(VROOM_CONNECTION_SIZE = 262144)  # Adjust the value as needed


# Example: Get defense statistics for all players in the 2018 Regular Season
result2021 <- teams_players_stats(
  seasons = 2021,
  types = "player",
  tables = c("defense","general"),
  season_types = "Regular Season",
  measures = c("Base"),
  modes = "PerGame",
  defenses = "Overall",
  is_plus_minus = FALSE,
  is_pace_adjusted = FALSE,
  periods = 0,
  is_rank = FALSE,
  game_segments = NA,
  divisions_against = NA,
  conferences_against = NA,
  date_from = NA,
  date_to = NA,
  last_n_games = 0,
  locations = NA,
  months = 0,
  season_segments = NA,
  opponents = NA,
  countries = NA,
  weights = NA,
  outcomes = NA,
  playoff_rounds = 0,
  players_experience = NA,
  players_positions = NA,
  colleges = NA,
  draft_picks = NA,
  draft_years = NA,
  game_scopes = NA,
  heights = NA,
  shot_clock_ranges = NA,
  clutch_times = NA,
  ahead_or_behind = "Ahead or Behind",
  general_ranges = "Overall",
  dribble_ranges = "0 Dribbles",
  shot_distance_ranges = "By Zone",
  touch_time_ranges = NA,
  closest_defender_ranges = NA,
  point_diffs = NA,
  starters_bench = NA,
  assign_to_environment = TRUE,
  add_mode_names = TRUE,
  return_message = TRUE
)

# Print the result
print(result2021)


# Print the result for all players
print(result2021$dataTable)

```

```{r}
trad_stats2021 <- dataGeneralPlayers
```

```{r}
def_stats2021 <- dataDefensePlayers
```

```{r}
# Example: Get year over year data for all players for the 2019 Regular Season
Sys.setenv(VROOM_CONNECTION_SIZE = 262144)  # Adjust the value as needed


# Example: Get defense statistics for all players in the 2018 Regular Season
result2 <- teams_players_stats(
  seasons = 2023,
  types = "player",
  tables = c("general"),
  season_types = "Regular Season",
  measures = c("Advanced"),
  modes = "PerGame",
  defenses = "Overall",
  is_plus_minus = FALSE,
  is_pace_adjusted = FALSE,
  periods = 0,
  is_rank = FALSE,
  game_segments = NA,
  divisions_against = NA,
  conferences_against = NA,
  date_from = NA,
  date_to = NA,
  last_n_games = 0,
  locations = NA,
  months = 0,
  season_segments = NA,
  opponents = NA,
  countries = NA,
  weights = NA,
  outcomes = NA,
  playoff_rounds = 0,
  players_experience = NA,
  players_positions = NA,
  colleges = NA,
  draft_picks = NA,
  draft_years = NA,
  game_scopes = NA,
  heights = NA,
  shot_clock_ranges = NA,
  clutch_times = NA,
  ahead_or_behind = "Ahead or Behind",
  general_ranges = "Overall",
  dribble_ranges = "0 Dribbles",
  shot_distance_ranges = "By Zone",
  touch_time_ranges = NA,
  closest_defender_ranges = NA,
  point_diffs = NA,
  starters_bench = NA,
  assign_to_environment = TRUE,
  add_mode_names = TRUE,
  return_message = TRUE
)

# Print the result
print(result2)


# Print the result for all players
print(result2$dataTable)
```
```{r}
adv_stats <- dataGeneralPlayers
```

```{r}
# Example: Get year over year data for all players for the 2019 Regular Season
Sys.setenv(VROOM_CONNECTION_SIZE = 262144)  # Adjust the value as needed


# Example: Get defense statistics for all players in the 2018 Regular Season
result2.2022 <- teams_players_stats(
  seasons = 2022,
  types = "player",
  tables = c("general"),
  season_types = "Regular Season",
  measures = c("Advanced"),
  modes = "PerGame",
  defenses = "Overall",
  is_plus_minus = FALSE,
  is_pace_adjusted = FALSE,
  periods = 0,
  is_rank = FALSE,
  game_segments = NA,
  divisions_against = NA,
  conferences_against = NA,
  date_from = NA,
  date_to = NA,
  last_n_games = 0,
  locations = NA,
  months = 0,
  season_segments = NA,
  opponents = NA,
  countries = NA,
  weights = NA,
  outcomes = NA,
  playoff_rounds = 0,
  players_experience = NA,
  players_positions = NA,
  colleges = NA,
  draft_picks = NA,
  draft_years = NA,
  game_scopes = NA,
  heights = NA,
  shot_clock_ranges = NA,
  clutch_times = NA,
  ahead_or_behind = "Ahead or Behind",
  general_ranges = "Overall",
  dribble_ranges = "0 Dribbles",
  shot_distance_ranges = "By Zone",
  touch_time_ranges = NA,
  closest_defender_ranges = NA,
  point_diffs = NA,
  starters_bench = NA,
  assign_to_environment = TRUE,
  add_mode_names = TRUE,
  return_message = TRUE
)

# Print the result
print(result2.2022)


# Print the result for all players
print(result2.2022$dataTable)
```

```{r}
adv_stats2022 <- dataGeneralPlayers
```


```{r}
# Example: Get year over year data for all players for the 2019 Regular Season
Sys.setenv(VROOM_CONNECTION_SIZE = 262144)  # Adjust the value as needed


# Example: Get defense statistics for all players in the 2018 Regular Season
result2.2021 <- teams_players_stats(
  seasons = 2021,
  types = "player",
  tables = c("general"),
  season_types = "Regular Season",
  measures = c("Advanced"),
  modes = "PerGame",
  defenses = "Overall",
  is_plus_minus = FALSE,
  is_pace_adjusted = FALSE,
  periods = 0,
  is_rank = FALSE,
  game_segments = NA,
  divisions_against = NA,
  conferences_against = NA,
  date_from = NA,
  date_to = NA,
  last_n_games = 0,
  locations = NA,
  months = 0,
  season_segments = NA,
  opponents = NA,
  countries = NA,
  weights = NA,
  outcomes = NA,
  playoff_rounds = 0,
  players_experience = NA,
  players_positions = NA,
  colleges = NA,
  draft_picks = NA,
  draft_years = NA,
  game_scopes = NA,
  heights = NA,
  shot_clock_ranges = NA,
  clutch_times = NA,
  ahead_or_behind = "Ahead or Behind",
  general_ranges = "Overall",
  dribble_ranges = "0 Dribbles",
  shot_distance_ranges = "By Zone",
  touch_time_ranges = NA,
  closest_defender_ranges = NA,
  point_diffs = NA,
  starters_bench = NA,
  assign_to_environment = TRUE,
  add_mode_names = TRUE,
  return_message = TRUE
)

# Print the result
print(result2.2021)


# Print the result for all players
print(result2.2021$dataTable)
```

```{r}
adv_stats2021 <- dataGeneralPlayers
```



```{r}
# Example: Get year over year data for all players for the 2019 Regular Season
Sys.setenv(VROOM_CONNECTION_SIZE = 262144)  # Adjust the value as needed


# Example: Get defense statistics for all players in the 2018 Regular Season
result3 <- teams_players_stats(
  seasons = 2023,
  types = "player",
  tables = c("general"),
  season_types = "Regular Season",
  measures = c("Usage"),
  modes = "PerGame",
  defenses = "Overall",
  is_plus_minus = FALSE,
  is_pace_adjusted = FALSE,
  periods = 0,
  is_rank = FALSE,
  game_segments = NA,
  divisions_against = NA,
  conferences_against = NA,
  date_from = NA,
  date_to = NA,
  last_n_games = 0,
  locations = NA,
  months = 0,
  season_segments = NA,
  opponents = NA,
  countries = NA,
  weights = NA,
  outcomes = NA,
  playoff_rounds = 0,
  players_experience = NA,
  players_positions = NA,
  colleges = NA,
  draft_picks = NA,
  draft_years = NA,
  game_scopes = NA,
  heights = NA,
  shot_clock_ranges = NA,
  clutch_times = NA,
  ahead_or_behind = "Ahead or Behind",
  general_ranges = "Overall",
  dribble_ranges = "0 Dribbles",
  shot_distance_ranges = "By Zone",
  touch_time_ranges = NA,
  closest_defender_ranges = NA,
  point_diffs = NA,
  starters_bench = NA,
  assign_to_environment = TRUE,
  add_mode_names = TRUE,
  return_message = TRUE
)

# Print the result
print(result3)


# Print the result for all players
print(result3$dataTable)
```

```{r}
usage_stats <- dataGeneralPlayers
```



```{r}
# Example: Get year over year data for all players for the 2019 Regular Season
Sys.setenv(VROOM_CONNECTION_SIZE = 262144)  # Adjust the value as needed


# Example: Get defense statistics for all players in the 2018 Regular Season
result3.2022 <- teams_players_stats(
  seasons = 2022,
  types = "player",
  tables = c("general"),
  season_types = "Regular Season",
  measures = c("Usage"),
  modes = "PerGame",
  defenses = "Overall",
  is_plus_minus = FALSE,
  is_pace_adjusted = FALSE,
  periods = 0,
  is_rank = FALSE,
  game_segments = NA,
  divisions_against = NA,
  conferences_against = NA,
  date_from = NA,
  date_to = NA,
  last_n_games = 0,
  locations = NA,
  months = 0,
  season_segments = NA,
  opponents = NA,
  countries = NA,
  weights = NA,
  outcomes = NA,
  playoff_rounds = 0,
  players_experience = NA,
  players_positions = NA,
  colleges = NA,
  draft_picks = NA,
  draft_years = NA,
  game_scopes = NA,
  heights = NA,
  shot_clock_ranges = NA,
  clutch_times = NA,
  ahead_or_behind = "Ahead or Behind",
  general_ranges = "Overall",
  dribble_ranges = "0 Dribbles",
  shot_distance_ranges = "By Zone",
  touch_time_ranges = NA,
  closest_defender_ranges = NA,
  point_diffs = NA,
  starters_bench = NA,
  assign_to_environment = TRUE,
  add_mode_names = TRUE,
  return_message = TRUE
)

# Print the result
print(result3.2022)


# Print the result for all players
print(result3.2022$dataTable)
```

```{r}
usage_stats2022 <- dataGeneralPlayers
```



```{r}
# Example: Get year over year data for all players for the 2019 Regular Season
Sys.setenv(VROOM_CONNECTION_SIZE = 262144)  # Adjust the value as needed


# Example: Get defense statistics for all players in the 2018 Regular Season
result3.2021 <- teams_players_stats(
  seasons = 2021,
  types = "player",
  tables = c("general"),
  season_types = "Regular Season",
  measures = c("Usage"),
  modes = "PerGame",
  defenses = "Overall",
  is_plus_minus = FALSE,
  is_pace_adjusted = FALSE,
  periods = 0,
  is_rank = FALSE,
  game_segments = NA,
  divisions_against = NA,
  conferences_against = NA,
  date_from = NA,
  date_to = NA,
  last_n_games = 0,
  locations = NA,
  months = 0,
  season_segments = NA,
  opponents = NA,
  countries = NA,
  weights = NA,
  outcomes = NA,
  playoff_rounds = 0,
  players_experience = NA,
  players_positions = NA,
  colleges = NA,
  draft_picks = NA,
  draft_years = NA,
  game_scopes = NA,
  heights = NA,
  shot_clock_ranges = NA,
  clutch_times = NA,
  ahead_or_behind = "Ahead or Behind",
  general_ranges = "Overall",
  dribble_ranges = "0 Dribbles",
  shot_distance_ranges = "By Zone",
  touch_time_ranges = NA,
  closest_defender_ranges = NA,
  point_diffs = NA,
  starters_bench = NA,
  assign_to_environment = TRUE,
  add_mode_names = TRUE,
  return_message = TRUE
)

# Print the result
print(result3.2021)


# Print the result for all players
print(result3.2021$dataTable)
```

```{r}
usage_stats2021 <- dataGeneralPlayers
```



```{r}
library(dplyr)

contract_stats <- contract_stats %>%
  select(Player, Tm, X2023.24) %>%
  rename(Team = Tm, 
         Year_2324 = X2023.24)

contract_stats2022 <- contract_stats2022 %>%
  select(Player, X2021.22) %>%
  rename(Year_2122 = X2021.22)

contract_stats2023 <- contract_stats2023 %>%
  select(Player, X2022.23) %>%
  rename(Year_2223 = X2022.23)
```

```{r}

library(stringr)

contract_stats1 <- contract_stats %>%
  mutate(Year_2324 = sapply(str_extract_all(Year_2324, '[[:digit:]]+'), function(x) as.numeric(paste(x, collapse = ''))))

contract_stats2022.2 <- contract_stats2022 %>%
  mutate(Year_2122 = sapply(str_extract_all(Year_2122, '[[:digit:]]+'), function(x) as.numeric(paste(x, collapse = ''))))

contract_stats2023.2 <- contract_stats2023 %>%
  mutate(Year_2223 = sapply(str_extract_all(Year_2223, '[[:digit:]]+'), function(x) as.numeric(paste(x, collapse = ''))))

```

```{r}
contract_stats1 <- contract_stats1 %>%
  distinct(Player, .keep_all = TRUE)

contract_stats2022.2 <- contract_stats2022.2 %>%
  distinct(Player, .keep_all = TRUE)

contract_stats2023.2 <- contract_stats2023.2 %>%
  distinct(Player, .keep_all = TRUE)

```


```{r}
raptor_stats <- raptor_stats %>%
  select(-c(war_total,war_playoffs, raptor_box_total, raptor_box_total, raptor_total, predator_total, raptor_onoff_total, player_id))

raptor_stats2021 <- raptor_stats2021 %>%
  select(-c(war_total,war_playoffs, raptor_box_total, raptor_box_total, raptor_total, predator_total, raptor_onoff_total, player_id))

raptor_stats2022 <- raptor_stats2022 %>%
  select(-c(war_total,war_playoffs, raptor_box_total, raptor_box_total, raptor_total, predator_total, raptor_onoff_total, player_id))


```

```{r}
def_stats1 <- def_stats %>%
  select(yearSeason, namePlayer, agePlayer,  gp, slugTeam, idPlayer, idPlayerTeam, fgmDefending, fgaDefending, pctFGDefending, pctFGAvg, diffFGPct)

def_stats1.2022 <- def_stats2022 %>%
  select(yearSeason, namePlayer, agePlayer,  gp, slugTeam, idPlayer, idPlayerTeam, fgmDefending, fgaDefending, pctFGDefending, pctFGAvg, diffFGPct)

def_stats1.2021 <- def_stats2021 %>%
  select(yearSeason, namePlayer, agePlayer,  gp, slugTeam, idPlayer, idPlayerTeam, fgmDefending, fgaDefending, pctFGDefending, pctFGAvg, diffFGPct)
  
```

```{r}
usage_stats1 <- usage_stats %>%
  select(yearSeason, namePlayer, agePlayer, gp, slugTeam, idPlayer, idTeam, minutes, pctUSG, pctFGMOfTeam, pctFGAOfTeam, pctFG3MOfTeam, pctFG3AOfTeam, pctFTMOfTeam, pctFTAOfTeam, pctOREBOfTeam, pctDREBOfTeam, pctREBOfTeam, pctASTOfTeam, pctTOVOfTeam, pctSTLOfTeam, pctBLKOfTeam, pctBLKAOfTeam, pctPFOfTeam, pctPFDOfTeam, pctPTSOfTeam)

usage_stats1.2022 <- usage_stats2022 %>%
  select(yearSeason, namePlayer, agePlayer, gp, slugTeam, idPlayer, idTeam, minutes, pctUSG, pctFGMOfTeam, pctFGAOfTeam, pctFG3MOfTeam, pctFG3AOfTeam, pctFTMOfTeam, pctFTAOfTeam, pctOREBOfTeam, pctDREBOfTeam, pctREBOfTeam, pctASTOfTeam, pctTOVOfTeam, pctSTLOfTeam, pctBLKOfTeam, pctBLKAOfTeam, pctPFOfTeam, pctPFDOfTeam, pctPTSOfTeam)

usage_stats1.2021 <- usage_stats2021 %>%
  select(yearSeason, namePlayer, agePlayer, gp, slugTeam, idPlayer, idTeam, minutes, pctUSG, pctFGMOfTeam, pctFGAOfTeam, pctFG3MOfTeam, pctFG3AOfTeam, pctFTMOfTeam, pctFTAOfTeam, pctOREBOfTeam, pctDREBOfTeam, pctREBOfTeam, pctASTOfTeam, pctTOVOfTeam, pctSTLOfTeam, pctBLKOfTeam, pctBLKAOfTeam, pctPFOfTeam, pctPFDOfTeam, pctPTSOfTeam)

```

```{r}
trad_stats1 <- trad_stats %>% 
  select(c(1:53))

trad_stats1.2022 <- trad_stats2022 %>% 
  select(c(1:53))

trad_stats1.2021 <- trad_stats2021 %>% 
  select(c(1:53))
```

```{r}
trad_stats2 <- trad_stats1 %>%
  select(yearSeason, namePlayer, agePlayer, gp, slugTeam, idPlayer, idTeam, minutes, fgm, fga, pctFG, fg3m, fg3a, pctFG3, ftm, fta, pctFT, fg2m, fg2a, pctFG2, oreb, dreb, treb, ast, tov, stl, blk, blka, pf, pfd, pts, plusminus, dd2, td3)

trad_stats2.2022 <- trad_stats1.2022 %>%
  select(yearSeason, namePlayer, agePlayer, gp, slugTeam, idPlayer, idTeam, minutes, fgm, fga, pctFG, fg3m, fg3a, pctFG3, ftm, fta, pctFT, fg2m, fg2a, pctFG2, oreb, dreb, treb, ast, tov, stl, blk, blka, pf, pfd, pts, plusminus, dd2, td3)

trad_stats2.2021 <- trad_stats1.2021 %>%
  select(yearSeason, namePlayer, agePlayer, gp, slugTeam, idPlayer, idTeam, minutes, fgm, fga, pctFG, fg3m, fg3a, pctFG3, ftm, fta, pctFT, fg2m, fg2a, pctFG2, oreb, dreb, treb, ast, tov, stl, blk, blka, pf, pfd, pts, plusminus, dd2, td3)
```

```{r}
adv_stats1 <- adv_stats %>%
  select(c(1:64))

adv_stats1.2022 <- adv_stats2022 %>%
  select(c(1:64))

adv_stats1.2021 <- adv_stats2021 %>%
  select(c(1:64))
```

```{r}
adv_stats2 <- adv_stats1 %>%
  select(yearSeason, namePlayer, agePlayer, gp, slugTeam, idPlayer, idTeam, minutes, possessions, pctAST, pctOREB, pctDREB, pctTREB, pctTOVTeam, pctTOVE, pctEFG, pctTS, pctUSG, pctUSGE, fgm, fga, fgmPerGame, fgaPerGame, pctFG, ortgE, ortg, removeOFF_RATING, drtgE, drtg, removeDEF_RATING, netrtgE, netrtg, removeNET_RATING, ratioASTtoTO, ratioAST, paceE, pace, pacePer40PACE_PER40, removePACE, ratioPIE)

adv_stats2.2022 <- adv_stats1.2022 %>%
  select(yearSeason, namePlayer, agePlayer, gp, slugTeam, idPlayer, idTeam, minutes, possessions, pctAST, pctOREB, pctDREB, pctTREB, pctTOVTeam, pctTOVE, pctEFG, pctTS, pctUSG, pctUSGE, fgm, fga, fgmPerGame, fgaPerGame, pctFG, ortgE, ortg, removeOFF_RATING, drtgE, drtg, removeDEF_RATING, netrtgE, netrtg, removeNET_RATING, ratioASTtoTO, ratioAST, paceE, pace, pacePer40PACE_PER40, removePACE, ratioPIE)

adv_stats2.2021 <- adv_stats1.2021 %>%
  select(yearSeason, namePlayer, agePlayer, gp, slugTeam, idPlayer, idTeam, minutes, possessions, pctAST, pctOREB, pctDREB, pctTREB, pctTOVTeam, pctTOVE, pctEFG, pctTS, pctUSG, pctUSGE, fgm, fga, fgmPerGame, fgaPerGame, pctFG, ortgE, ortg, removeOFF_RATING, drtgE, drtg, removeDEF_RATING, netrtgE, netrtg, removeNET_RATING, ratioASTtoTO, ratioAST, paceE, pace, pacePer40PACE_PER40, removePACE, ratioPIE)
```

```{r}
raptor_contract_stats <- merge(contract_stats1, raptor_stats, by.x = "Player", by.y = "player_name", all.x = FALSE, all.y = FALSE)

raptor_contract_stats2022 <- merge(contract_stats2023.2, raptor_stats2022, by.x = "Player", by.y = "player_name", all.x = FALSE, all.y = FALSE)

raptor_contract_stats2021 <- merge(contract_stats2022.2, raptor_stats2021, by.x = "Player", by.y = "player_name", all.x = FALSE, all.y = FALSE)

```



```{r}
total_stats <- trad_stats2 %>%
  left_join(def_stats1, by = "idPlayer") %>%
  left_join(adv_stats2, by = "idPlayer") %>%
  left_join(trad_stats2, by = "idPlayer")

total_stats2022 <- trad_stats2.2022 %>%
  left_join(def_stats1.2022, by = "idPlayer") %>%
  left_join(adv_stats2.2022, by = "idPlayer") %>%
  left_join(trad_stats2.2022, by = "idPlayer")

total_stats2021 <- trad_stats2.2021 %>%
  left_join(def_stats1.2021, by = "idPlayer") %>%
  left_join(adv_stats2.2021, by = "idPlayer") %>%
  left_join(trad_stats2.2021, by = "idPlayer")
```

```{r}
total_stats2 <- rbind(total_stats, total_stats2021, total_stats2022)
```

```{r}
raptor_contract_stats <- raptor_contract_stats %>% 
  select(-c(Team)) %>%
  rename(Salary = Year_2324) 

raptor_contract_stats2022 <- raptor_contract_stats2022 %>%
  rename(Salary = Year_2223)

raptor_contract_stats2021 <- raptor_contract_stats2021 %>%
  rename(Salary = Year_2122)

```


```{r}
raptor_contract_stats2 <- rbind(raptor_contract_stats, 
                                     raptor_contract_stats2022, 
                                     raptor_contract_stats2021)
```




```{r}
total_stats1 <- total_stats2 %>%
  select(-c(namePlayer.y, namePlayer.x.x, namePlayer.y.y, agePlayer.y, agePlayer.x.x, agePlayer.y.y, gp.y, gp.x.x, gp.y.y, slugTeam.y, slugTeam.x.x, slugTeam.y.y, idTeam.x, idTeam.y, idTeam))
```


```{r}
perf_contract_stats2 <- merge(raptor_contract_stats2, total_stats1, 
                              by.x = c("Player", "season"), 
                              by.y = c("namePlayer.x", "yearSeason.x"), 
                              all.x = FALSE, all.y = FALSE)

```

```{r}

```


```{r}
perf_contract_stats2 <- perf_contract_stats2 %>%
  mutate(SalaryToCapRatio = ifelse(season == 2021, Salary/112414000,
                           ifelse(season == 2022, Salary/123655000,
                                  ifelse(season == 2023, Salary/136021000, NA))))
```


```{r}
perf_contract_stats3 <- perf_contract_stats2 %>%
  select(-c(removeOFF_RATING, removeDEF_RATING, removeNET_RATING, season, slugTeam.x, fgm.x, fgm, fga.x, fga, ftm.y, fta.y, oreb.y, dreb.y, ast.y, tov.y, dd2.y, td3.y, plusminus.y, pts.y, pfd.y, blka.y, pf.y, blk.y, stl.y, pctFG2.y, treb.y, fg2m.y, fg2a.y, pctFT.y, pctFG3.y, fg3m.y, fg3a.y, minutes.y, poss, pctFG.x, pctFG.y))
```





```{r}
perf_contract_stats4 <- perf_contract_stats3 %>%
  filter(mp >= 500 | minutes.x >= 11.0) %>%
  filter(Player!= "Rudy Gay")
```





```{r}
set.seed(11111)
sample <- sample.split(perf_contract_stats4$SalaryToCapRatio, SplitRatio = 0.7)
nba_train  <- subset(perf_contract_stats4, sample == TRUE)
nba_test   <- subset(perf_contract_stats4, sample == FALSE)
dim(nba_train)
dim(nba_test)
head(nba_train)


```




```{r}

nba_regression_train <- nba_train  %>%
  select(c(,4:13,15,18:36,38:40,43:47,49:59,63:76,79,80))
nba_regression_test <- nba_test  %>%
  select(-c(Player, mp, agePlayer.x, idPlayer, idPlayerTeam, minutes.x))

NBAfit1 <- lm(SalaryToCapRatio ~ ., data = nba_regression_train)
summary(NBAfit1)
```

```{r}
dtrain <- xgb.DMatrix(data = as.matrix(nba_train[,c(4:13,15,18:36,38:40,43:47,49:59,63:76,79)]), label = as.numeric(nba_train$SalaryToCapRatio))

# Create test matrix



dtest <-  xgb.DMatrix(data = as.matrix(nba_test[,c(4:13,15,18:36,38:40,43:47,49:59,63:76,79)]), label = as.numeric(nba_test$SalaryToCapRatio))
```

```{r}
set.seed(111111)
bst_1 <- xgboost(data = dtrain, # Set training data
               
               nrounds = 100, # Set number of rounds
               
               verbose = 1, # 1 - Prints out fit
                print_every_n = 20) # Prints out result every 20th iteration
```

```{r}
set.seed(111111)
bst <- xgb.cv(data = dtrain, # Set training data
              
              nfold = 5, # Use 5 fold cross-validation
               
               eta = 0.1, # Set learning rate
              
               nrounds = 1000, # Set number of rounds
               early_stopping_rounds = 50, # Set number of rounds to stop at if there is no improvement
               
               verbose = 1, # 1 - Prints out fit
               nthread = 1, # Set number of parallel threads
               print_every_n = 20) # Prints out result every 20th iteration
```

From this we see 77 was the optimal number of iterations for our model. We use this number solely to ensure that we are doing a sufficient amount of rounds for our next tuning stages. We will set the number of iterations to 100 and include an early stop parameter of 20 for our next round of tuning.

```{r}
max_depth_vals <- c(3, 5, 7, 10, 15) # Create vector of max depth values
min_child_weight <- c(1,3,5,7, 10, 15) # Create vector of min child values

# Expand grid of parameter values
cv_params <- expand.grid(max_depth_vals, min_child_weight)
names(cv_params) <- c("max_depth", "min_child_weight")
# Create results vector
rmse_vec  <- rep(NA, nrow(cv_params)) 
# Loop through results
for(i in 1:nrow(cv_params)){
  set.seed(111111)
  bst_tune <- xgb.cv(data = dtrain, # Set training data
                     
                     nfold = 5, # Use 5 fold cross-validation
                     
                     eta = 0.1, # Set learning rate
                     max.depth = cv_params$max_depth[i], # Set max depth
                     min_child_weight = cv_params$min_child_weight[i], # Set minimum number of samples in node to split
                     
                     
                     nrounds = 1000, # Set number of rounds
                     early_stopping_rounds = 50, # Set number of rounds to stop at if there is no improvement
                     
                     verbose = 1, # 1 - Prints out fit
                     nthread = 1, # Set number of parallel threads
                     print_every_n = 20 # Prints out result every 20th iteration
                     
  ) # Set evaluation metric to use
  
  rmse_vec[i] <- bst_tune$evaluation_log$test_rmse_mean[bst_tune$best_ntreelimit]
  
  
}
```
Best is 49:

```{r}
# Join results in dataset
res_db <- cbind.data.frame(cv_params, rmse_vec)
names(res_db)[3] <- c("rmse") 
res_db$max_depth <- as.factor(res_db$max_depth) # Convert tree number to factor for plotting
res_db$min_child_weight <- as.factor(res_db$min_child_weight) # Convert node size to factor for plotting
# Print AUC heatmap
g_2 <- ggplot(res_db, aes(y = max_depth, x = min_child_weight, fill = rmse)) + # set aesthetics
  geom_tile() + # Use geom_tile for heatmap
  theme_bw() + # Set theme
  scale_fill_gradient2(low = "blue", # Choose low color
                       mid = "white", # Choose mid color
                       high = "red", # Choose high color
                       midpoint =mean(res_db$rmse), # Choose mid point
                       space = "Lab", 
                       na.value ="grey", # Choose NA value
                       guide = "colourbar", # Set color bar
                       aesthetics = "fill") + # Select aesthetics to apply
  labs(x = "Minimum Child Weight", y = "Max Depth", fill = "RMSE") # Set labels
g_2 # Generate plot
```

```{r}
res_db[which.min(res_db$rmse),] 
```

```{r}
gamma_vals <- c(0, 0.05, 0.1, 0.15, 0.2) # Create vector of gamma values

# Be Careful - This can take a very long time to run
set.seed(111111)
rmse_vec  <- rep(NA, length(gamma_vals))
for(i in 1:length(gamma_vals)){
  bst_tune <- xgb.cv(data = dtrain, # Set training data
                     
                     nfold = 5, # Use 5 fold cross-validation
                     
                     eta = 0.1, # Set learning rate
                     max.depth = 7, # Set max depth
                     min_child_weight = 15, # Set minimum number of samples in node to split
                     gamma = gamma_vals[i], # Set minimum loss reduction for split
                     
                     
                     
                     nrounds = 1000, # Set number of rounds
                     early_stopping_rounds = 50, # Set number of rounds to stop at if there is no improvement
                     
                     verbose = 1, # 1 - Prints out fit
                     nthread = 1, # Set number of parallel threads
                     print_every_n = 20 # Prints out result every 20th iteration
  ) # Set evaluation metric to use
  
  
  rmse_vec[i] <- bst_tune$evaluation_log$test_rmse_mean[bst_tune$best_ntreelimit]
  
  
}
```
best 164


```{r}
cbind.data.frame(gamma_vals, rmse_vec)
```

```{r}
###### 3 - Subsample and Column sample Tuning ######

# Be Careful - This can take a very long time to run
subsample <- c(0.6, 0.7, 0.8, 0.9, 1) # Create vector of subsample values
colsample_by_tree <- c(0.6, 0.7, 0.8, 0.9, 1) # Create vector of col sample values

# Expand grid of tuning parameters
cv_params <- expand.grid(subsample, colsample_by_tree)
names(cv_params) <- c("subsample", "colsample_by_tree")
# Create vectors to store results
rmse_vec <- rep(NA, nrow(cv_params)) 
# Loop through parameter values
for(i in 1:nrow(cv_params)){
  set.seed(111111)
  bst_tune <- xgb.cv(data = dtrain, # Set training data
                     
                     nfold = 5, # Use 5 fold cross-validation
                     
                     eta = 0.1, # Set learning rate
                     max.depth = 7, # Set max depth
                     min_child_weight = 15, # Set minimum number of samples in node to split
                     gamma = 0.05, # Set minimum loss reduction for split
                     subsample = cv_params$subsample[i], # Set proportion of training data to use in tree
                     colsample_bytree = cv_params$colsample_by_tree[i], # Set number of variables to use in each tree
                     
                     nrounds = 1000, # Set number of rounds
                     early_stopping_rounds = 50, # Set number of rounds to stop at if there is no improvement
                     
                     verbose = 1, # 1 - Prints out fit
                     nthread = 1, # Set number of parallel threads
                     print_every_n = 20 # Prints out result every 20th iteration
  ) # Set evaluation metric to use
  
  
  rmse_vec[i] <- bst_tune$evaluation_log$test_rmse_mean[bst_tune$best_ntreelimit]
  
  
}
```

165

```{r}
res_db <- cbind.data.frame(cv_params, rmse_vec)
names(res_db)[3] <- c("rmse") 
res_db$subsample <- as.factor(res_db$subsample) # Convert tree number to factor for plotting
res_db$colsample_by_tree <- as.factor(res_db$colsample_by_tree) # Convert node size to factor for plotting
g_4 <- ggplot(res_db, aes(y = colsample_by_tree, x = subsample, fill = rmse)) + # set aesthetics
  geom_tile() + # Use geom_tile for heatmap
  theme_bw() + # Set theme
  scale_fill_gradient2(low = "blue", # Choose low color
                       mid = "white", # Choose mid color
                       high = "red", # Choose high color
                       midpoint =mean(res_db$rmse), # Choose mid point
                       space = "Lab", 
                       na.value ="grey", # Choose NA value
                       guide = "colourbar", # Set color bar
                       aesthetics = "fill") + # Select aesthetics to apply
  labs(x = "Subsample", y = "Column Sample by Tree", fill = "RMSE") # Set labels
g_4 # Generate plot
```


```{r}
res_db
```


```{r}
res_db[which.min(res_db$rmse),]
```

```{r}
###### 4 - eta tuning ######

# Use xgb.cv to run cross-validation inside xgboost
set.seed(111111)
bst_mod_1 <- xgb.cv(data = dtrain, # Set training data
                    
                    nfold = 5, # Use 5 fold cross-validation
                    
                    eta = 0.3, # Set learning rate
                    max.depth = 7, # Set max depth
                    min_child_weight = 15, # Set minimum number of samples in node to split
                    gamma = .05, # Set minimum loss reduction for split
                    subsample = .7, # Set proportion of training data to use in tree
                    colsample_bytree =  .8, # Set number of variables to use in each tree
                    
                    nrounds = 1000, # Set number of rounds
                    early_stopping_rounds = 50, # Set number of rounds to stop at if there is no improvement
                    
                    verbose = 1, # 1 - Prints out fit
                    nthread = 1, # Set number of parallel threads
                    print_every_n = 20 # Prints out result every 20th iteration
) # Set evaluation metric to use
```


```{r}
set.seed(111111)
bst_mod_2 <- xgb.cv(data = dtrain, # Set training data
                    
                    nfold = 5, # Use 5 fold cross-validation
                    
                    eta = 0.1, # Set learning rate
                    max.depth =  7, # Set max depth
                    min_child_weight = 15, # Set minimum number of samples in node to split
                    gamma = .05, # Set minimum loss reduction for split
                    subsample = .7, # Set proportion of training data to use in tree
                    colsample_bytree = .8, # Set number of variables to use in each tree
                    
                    nrounds = 1000, # Set number of rounds
                    early_stopping_rounds = 50, # Set number of rounds to stop at if there is no improvement
                    
                    verbose = 1, # 1 - Prints out fit
                    nthread = 1, # Set number of parallel threads
                    print_every_n = 20 # Prints out result every 20th iteration
) # Set evaluation metric to use
```


```{r}
set.seed(111111)
bst_mod_3 <- xgb.cv(data = dtrain, # Set training data
                    
                    nfold = 5, # Use 5 fold cross-validation
                    
                    eta = 0.05, # Set learning rate
                    max.depth = 7, # Set max depth
                    min_child_weight = 15, # Set minimum number of samples in node to split
                    gamma = .05, # Set minimum loss reduction for split
                    subsample = .7 , # Set proportion of training data to use in tree
                    colsample_bytree =  .8, # Set number of variables to use in each tree
                    
                    nrounds = 1000, # Set number of rounds
                    early_stopping_rounds = 50, # Set number of rounds to stop at if there is no improvement
                    
                    verbose = 1, # 1 - Prints out fit
                    nthread = 1, # Set number of parallel threads
                    print_every_n = 20 # Prints out result every 20th iteration
) # Set evaluation metric to use
```



```{r}
set.seed(111111)
bst_mod_4 <- xgb.cv(data = dtrain, # Set training data
                    
                    nfold = 5, # Use 5 fold cross-validation
                    
                    eta = 0.01, # Set learning rate
                    max.depth = 7, # Set max depth
                    min_child_weight = 15, # Set minimum number of samples in node to split
                    gamma = 0.05, # Set minimum loss reduction for split
                    subsample = .7, # Set proportion of training data to use in tree
                    colsample_bytree = .8, # Set number of variables to use in each tree
                    
                    nrounds = 1000, # Set number of rounds
                    early_stopping_rounds = 50, # Set number of rounds to stop at if there is no improvement
                    
                    verbose = 1, # 1 - Prints out fit
                    nthread = 1, # Set number of parallel threads
                    print_every_n = 20 # Prints out result every 20th iteration
) # Set evaluation metric to use
```



```{r}
set.seed(111111)
bst_mod_5 <- xgb.cv(data = dtrain, # Set training data
                    
                    nfold = 5, # Use 5 fold cross-validation
                    
                    eta = 0.005, # Set learning rate
                    max.depth = 7, # Set max depth
                    min_child_weight = 15, # Set minimum number of samples in node to split
                    gamma = .05, # Set minimum loss reduction for split
                    subsample = .7 , # Set proportion of training data to use in tree
                    colsample_bytree = .8, # Set number of variables to use in each tree
                    
                    nrounds = 1000, # Set number of rounds
                    early_stopping_rounds = 50, # Set number of rounds to stop at if there is no improvement
                    
                    verbose = 1, # 1 - Prints out fit
                    nthread = 1, # Set number of parallel threads
                    print_every_n = 20 # Prints out result every 20th iteration
                    
) # Set evaluation metric to use
```

```{r}
# Extract results for model with eta = 0.3
pd1 <- cbind.data.frame(bst_mod_1$evaluation_log[,c("iter", "test_rmse_mean")], rep(0.3, nrow(bst_mod_1$evaluation_log)))
names(pd1)[3] <- "eta"
# Extract results for model with eta = 0.1
pd2 <- cbind.data.frame(bst_mod_2$evaluation_log[,c("iter", "test_rmse_mean")], rep(0.1, nrow(bst_mod_2$evaluation_log)))
names(pd2)[3] <- "eta"
# Extract results for model with eta = 0.05
pd3 <- cbind.data.frame(bst_mod_3$evaluation_log[,c("iter", "test_rmse_mean")], rep(0.05, nrow(bst_mod_3$evaluation_log)))
names(pd3)[3] <- "eta"
# Extract results for model with eta = 0.01
pd4 <- cbind.data.frame(bst_mod_4$evaluation_log[,c("iter", "test_rmse_mean")], rep(0.01, nrow(bst_mod_4$evaluation_log)))
names(pd4)[3] <- "eta"
# Extract results for model with eta = 0.005
pd5 <- cbind.data.frame(bst_mod_5$evaluation_log[,c("iter", "test_rmse_mean")], rep(0.005, nrow(bst_mod_5$evaluation_log)))
names(pd5)[3] <- "eta"
# Join datasets
plot_data <- rbind.data.frame(pd1, pd2, pd3, pd4, pd5)
# Converty ETA to factor
plot_data$eta <- as.factor(plot_data$eta)
# Plot points
g_6 <- ggplot(plot_data, aes(x = iter, y = test_rmse_mean, color = eta))+
  geom_point(alpha = 0.5) +
  theme_bw() + # Set theme
  theme(panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) + # Remove grid 
  labs(x = "Number of Trees", title = "RMSE v Number of Trees",
       y = "RMSE", color = "Learning \n Rate")  # Set labels
g_6
```


```{r}
set.seed(111111)
bst_final <- xgboost(data = dtrain, # Set training data
                     
                     
                     
                     eta = .1, # Set learning rate
                     max.depth =  7, # Set max depth
                     min_child_weight = 15, # Set minimum number of samples in node to split
                     gamma = .05, # Set minimum loss reduction for split
                     subsample = .7, # Set proportion of training data to use in tree
                     colsample_bytree = .8, # Set number of variables to use in each tree
                     
                     nrounds = 1000, # Set number of rounds
                     early_stopping_rounds = 50, # Set number of rounds to stop at if there is no improvement
                     
                     verbose = 1, # 1 - Prints out fit
                     nthread = 1, # Set number of parallel threads
                     print_every_n = 20 # Prints out result every 20th iteration
                     
) # Set evaluation metric to use
```

```{r}
# Extract importance
imp_mat <- xgb.importance(model = bst_final)
# Plot importance (top 10 variables)
xgb.plot.importance(imp_mat, top_n = 10)
```


```{r}
getTreeBreakdown = function(tree, col_names){

  ####accepts a tree (data table), and column names
  ####outputs a data table, of the impact of each variable + intercept, for each leaf

  tree_breakdown <- vector("list", length(col_names)  + 2)
  names(tree_breakdown) = c(col_names,'intercept','leaf')

  leaves = tree[leaf==T, Node]

  for (leaf in leaves){

    leaf_breakdown = getLeafBreakdown(tree,leaf,col_names)
    leaf_breakdown$leaf = leaf
    tree_breakdown = rbindlist(append(list(tree_breakdown),list(leaf_breakdown)))
  }

  return (tree_breakdown)
}

buildExplainerFromTreeList = function(tree_list,col_names){
 
  ####accepts a list of trees and column names
  ####outputs a data table, of the impact of each variable + intercept, for each leaf

  tree_list_breakdown <- vector("list", length(col_names)  + 3)
  names(tree_list_breakdown) = c(col_names,'intercept', 'leaf','tree')

  num_trees = length(tree_list)
 
  cat('\n\nGetting breakdown for each leaf of each tree...\n')
  pb <- txtProgressBar(style=3)
 
  for (x in 1:num_trees){
    tree = tree_list[[x]]
    tree_breakdown = getTreeBreakdown(tree, col_names)
    tree_breakdown$tree = x - 1
    tree_list_breakdown = rbindlist(append(list(tree_list_breakdown),list(tree_breakdown)))
    setTxtProgressBar(pb, x / num_trees)
  }
 
  return (tree_list_breakdown)
 
}


getStatsForTrees = function(trees, nodes.train, type = "binary", base_score = 0.5){
  #Accepts data table of tree (the output of xgb.model.dt.tree)
  #Returns a list of tree, with the stats filled in
 
  tree_list = copy(trees)
  tree_list[,leaf := Feature == 'Leaf']
  tree_list[,H:=Cover]
 
  non.leaves = which(tree_list[,leaf]==F)

 
  # The default cover (H) seems to lose precision so this loop recalculates it for each node of each tree
  cat('\n\nRecalculating the cover for each non-leaf... \n')
  pb <- txtProgressBar(style=3)
  j = 0
  for (i in rev(non.leaves)){
    left = tree_list[i,Yes]
    right = tree_list[i,No]
    tree_list[i,H:=tree_list[ID==left,H] + tree_list[ID==right,H]]
    j=j+1
    setTxtProgressBar(pb, j / length(non.leaves))
  }
 

  if (type == 'regression'){
    base_weight = base_score
  } else{
    base_weight = log(base_score / (1-base_score))
  }
 
  tree_list[leaf==T,weight:=base_weight + Quality]
 
  tree_list[,previous_weight:=base_weight]
  tree_list[1,previous_weight:=0]
 
  tree_list[leaf==T,G:=-weight*H]
 
  tree_list = split(tree_list,as.factor(tree_list$Tree))
  num_tree_list = length(tree_list)
  treenums =  as.character(0:(num_tree_list-1))
  t = 0
  cat('\n\nFinding the stats for the xgboost trees...\n')
  pb <- txtProgressBar(style=3)
  for (tree in tree_list){
    t=t+1
    num_nodes = nrow(tree)
    non_leaf_rows = rev(which(tree[,leaf]==F))
    for (r in non_leaf_rows){
        left = tree[r,Yes]
        right = tree[r,No]
        leftG = tree[ID==left,G]
        rightG = tree[ID==right,G]
       
        tree[r,G:=leftG+rightG]
        w=tree[r,-G/H]
       
        tree[r,weight:=w]
        tree[ID==left,previous_weight:=w]
        tree[ID==right,previous_weight:=w]
    }
   
    tree[,uplift_weight:=weight-previous_weight]
    setTxtProgressBar(pb, t / num_tree_list)
  }
 
  return (tree_list)
}


getLeafBreakdown = function(tree,leaf,col_names){
 
  ####accepts a tree, the leaf id to breakdown and column names
  ####outputs a list of the impact of each variable + intercept
 
  impacts = as.list(rep(0,length(col_names)))
  names(impacts) = col_names
 
  path = findPath(tree,leaf)
  reduced_tree = tree[Node %in% path,.(Feature,uplift_weight)]
 
  impacts$intercept=reduced_tree[1,uplift_weight]
  reduced_tree[,uplift_weight:=shift(uplift_weight,type='lead')]
 
  tmp = reduced_tree[,.(sum=sum(uplift_weight)),by=Feature]
  tmp = tmp[-nrow(tmp)]
  impacts[tmp[,Feature]]=tmp[,sum]
 
  return (impacts)
}

findPath = function(tree, currentnode, path = c()){
 
  #accepts a tree data table, and the node to reach
  #path is used in the recursive function - do not set this
 
  while(currentnode>0){
    path = c(path,currentnode)
    currentlabel = tree[Node==currentnode,ID]
    currentnode = c(tree[Yes==currentlabel,Node],tree[No==currentlabel,Node])
  }
  return (sort(c(path,0)))
 
}


findLeaves = function(tree, currentnode){
 
  if (tree[currentnode,'Feature']=='Leaf'){
    leaves = currentnode
  }else{
    leftnode = tree[currentnode,Yes]
    rightnode = tree[currentnode,No]
    leaves = c(findLeaves(tree,'leftnode',with=FALSE),findLeaves(tree,'rightnode',with=FALSE))
  }
 
  return (sort(leaves))
 
 
}



buildExplainer = function(xgb.model,
                          trainingData,
                       
                          type = "binary", base_score = 0.5, trees_idx = NULL){

  col_names = colnames(trainingData)
  cat('\nCreating the trees of the xgboost model...')
  trees = xgb.model.dt.tree(col_names, model = xgb.model, trees = trees_idx)
  cat('\nGetting the leaf nodes for the training set observations...')
  nodes.train = predict(xgb.model,trainingData,predleaf =TRUE)

  cat('\nBuilding the Explainer...')
  cat('\nSTEP 1 of 2')
  tree_list = getStatsForTrees(trees, nodes.train, type = type, base_score = base_score)
  cat('\n\nSTEP 2 of 2')
  explainer = buildExplainerFromTreeList(tree_list,col_names)

  cat('\n\nDONE!\n\n')

  return (explainer)
}
```


```{r}
explainer = buildExplainer(bst_final, dtrain, type="regression", base_score = 0.5, trees_idx = NULL) # Create explainer
```
```{r}
pred.breakdown = explainPredictions(bst_final, explainer, dtest) # Breakdown predictions
```
```{r}
showWaterfall(bst_final, explainer, dtest, as.matrix(nba_test[, c(4:13,15,18:36,38:40,43:47,49:59,63:76,79)]) ,17, type = "regression", threshold = 0.07)
```

```{r}
showWaterfall(bst_final, explainer, dtest, as.matrix(nba_test[, c(4:13,15,18:36,38:40,43:47,49:59,63:76,79)]) ,1:320, type = "regression", threshold = 0.07)
```

```{r}
numeric_values <- c(0.120282, 0.1840695, 0.03176672, 0.03243895, 0.03073753, 0.03073753, 0.03544329, 0.1311503, 0.1109376, 0.09672666, 0.02674647, 0.05464206, 0.03365805, 0.1214725, 0.1321166, 0.1516603, 0.180128, 0.2559248, 0.04188401, 0.2357193, 0.2288761, 0.03257145, 0.08837092, 0.03185296, 0.03045591, 0.09670671, 0.115186, 0.0466443, 0.07291712, 0.03346813, 0.2476538, 0.2314071, 0.02852949, 0.04226834, 0.03185296, 0.02852949, 0.03176672, 0.1495983, 0.1158131, 0.1694418, 0.08406446, 0.05213753, 0.06869542, 0.1107722, 0.03530205, 0.04488123, 0.02852949, 0.1026874, 0.1534278, 0.1746231, 0.03288215, 0.03437493, 0.03028921, 0.04461877, 0.03185296, 0.1589136, 0.03185296, 0.03015155, 0.02852949, 0.2401097, 0.03513096, 0.03023091, 0.04349092, 0.03015155, 0.03073753, 0.1147953, 0.08544947, 0.02852949, 0.03118073, 0.08284008, 0.03185296, 0.1064042, 0.05871362, 0.03126009, 0.03185296, 0.03607634, 0.1551474, 0.07002178, 0.2288918, 0.05946203, 0.04880071, 0.04834289, 0.2561887, 0.02852949, 0.1162161, 0.235495, 0.1822124, 0.0683149, 0.0465215, 0.03197857, 0.1531299, 0.03853542, 0.07004074, 0.05387761, 0.03015155, 0.03365805, 0.07307781, 0.03894355, 0.1501793, 0.1713778, 0.04358542, 0.04823541, 0.06192731, 0.03015155, 0.2104074, 0.2392938, 0.04407194, 0.03346813, 0.0440769, 0.03513096, 0.03410178, 0.02911548, 0.04151522, 0.03836535, 0.2842315, 0.03204511, 0.03185296, 0.07577258, 0.05908245, 0.1261118, 0.03185296, 0.06563252, 0.03262887, 0.1025951, 0.03903084, 0.03243895, 0.03804541, 0.0438134, 0.05362339, 0.04973475, 0.2146485, 0.2535458, 0.2676827, 0.1068135, 0.02852949, 0.1058446, 0.086239, 0.03270822, 0.07344377, 0.2726269, 0.05173239,  0.03082948, 0.03346813, 0.2172107, 0.07696915, 0.1709943, 0.02852949, 0.03709901, 0.03382812, 0.2440731, 0.02852949, 0.03073753, 0.3020876, 0.1373814, 0.1834813, 0.03530205, 0.1121062, 0.278937, 0.196171, 0.1527369, 0.03441411, 0.1928596, 0.04568874, 0.03023091, 0.1666838, 0.03454498, 0.1530126, 0.1592404, 0.03023091, 0.09297858, 0.03185296, 0.07610226, 0.1324491, 0.03346813, 0.03418662, 0.04382893, 0.2314984, 0.2460606, 0.3057463, 0.07687851, 0.1361023, 0.0447851, 0.194113, 0.05820605, 0.03882071, 0.03882071, 0.03617705, 0.04600532, 0.08092932, 0.03321485, 0.1641269, 0.03702229, 0.03872371, 0.2410555, 0.1965156, 0.1290764, 0.03185296, 0.1265231, 0.02852949, 0.239629, 0.07258283, 0.1345668, 0.1902209, 0.1733992, 0.09380942, 0.03185296, 0.03185296, 0.07742725, 0.2129946, 0.191513, 0.04829014, 0.09846415, 0.2786233, 0.2877257, 0.2763976, 0.03315743, 0.1336375, 0.04480557, 0.03714471, 0.07603192, 0.06219621, 0.03262887, 0.2195427, 0.02852949, 0.1505932, 0.03118073, 0.03073753, 0.03552954, 0.06928809, 0.07557925, 0.06743759, 0.05412986, 0.08480453, 0.03957633, 0.05507875, 0.07350335, 0.06400567, 0.117648, 0.03159279, 0.04192207, 0.05276218, 0.1854782, 0.03015155, 0.04451386, 0.03023091, 0.03118073, 0.04396976, 0.1379647, 0.05138682, 0.2934049, 0.1511232, 0.1345533, 0.03185296, 0.03203691, 0.03455117, 0.1302915, 0.123901, 0.03321485, 0.06472856, 0.03015155, 0.08082898, 0.2090042, 0.03947976, 0.02852949, 0.03427286, 0.03535946, 0.06735393, 0.05434056, 0.04489752, 0.1690428, 0.1775359, 0.1052955, 0.06573358, 0.07771071, 0.03243895, 0.02852949, 0.199494, 0.05306936, 0.2270256, 0.09664847, 0.1146289, 0.08277448, 0.1729271,  0.1007919, 0.03787491, 0.07372367, 0.09417141, 0.03288215, 0.08124201, 0.26034, 0.2342565, 0.301078, 0.03382812, 0.03118073, 0.06255632, 0.03176672, 0.03872371, 0.1497021, 0.03185296, 0.03185296, 0.0504311, 0.02852949, 0.0389041, 0.03015155, 0.03787491, 0.03243895, 0.2496452, 0.03118073, 0.05500547, 0.1056227, 0.04834572, 0.08469205, 0.04223803, 0.1111, 0.1010783, 0.03015155, 0.032936, 0.09690166, 0.08419045, 0.05533381)

# Create a data frame with a column named 'values'
nba_test$prediction <- data.frame(prediction = numeric_values)

nba_test$prediction

```









```{r}
pred.breakdown = explainPredictions(bst_final, explainer, dtrain) # Breakdown predictions
```

```{r}
showWaterfall(bst_final, explainer, dtrain, as.matrix(nba_train[, c(4:13,15,18:36,38:40,43:47,49:59,63:76,79)]) ,1:746, type = "regression", threshold = 0.07)
```

```{r}
# Your list of numeric values
numeric_values <- c(0.09404786, 0.03015155, 0.0324036, 0.03028921, 0.03424403, 0.03015155, 0.03081689, 0.0431789, 0.09673428, 0.08370267, 0.08171815, 0.04794465, 0.03408143, 0.04052212, 0.05803081, 0.03262887, 0.05156816, 0.1387675, 0.03346813, 0.02852949, 0.1151781, 0.06905285, 0.0353976, 0.03288215, 0.04469116, 0.03597038, 0.1698228, 0.04234906, 0.1324522, 0.2630775, 0.2448041, 0.2740333, 0.09742519, 0.03015155, 0.02911548, 0.06565215, 0.03315743, 0.09875698, 0.03427286, 0.03288215, 0.02911548, 0.03535946, 0.03424403, 0.2336005, 0.2389039, 0.09527198, 0.03373741, 0.03185296, 0.105971, 0.03599311, 0.1410848, 0.08853371, 0.1447556, 0.1294565, 0.1150809, 0.1268652, 0.1318588, 0.0506898, 0.2525927, 0.04165205, 0.04923337, 0.2411402, 0.2616695, 0.2468394, 0.02930631, 0.03015155, 0.1039679, 0.06740579, 0.1285792, 0.05470651, 0.04667601, 0.05200204, 0.03727721, 0.1471782, 0.1415497, 0.03073753, 0.03185296, 0.0421542, 0.05542753, 0.0616713, 0.04038479, 0.02733246, 0.03176672, 0.03952953, 0.04268277, 0.1454415, 0.03729116, 0.05982782, 0.1875231, 0.09634484, 0.07385762, 0.04827832, 0.03073753, 0.03015155, 0.0466443, 0.03015155, 0.06895203, 0.0579756, 0.06054496, 0.03321485, 0.1510491, 0.1869336, 0.1183241, 0.1336294, 0.03023091, 0.2207268, 0.2211059, 0.1880462, 0.1770174, 0.1177984, 0.1176206, 0.1001853, 0.06216471, 0.04798048, 0.0449746, 0.02852949, 0.05404575, 0.03015155, 0.03023091, 0.06270002, 0.1244679, 0.08760193, 0.1072042, 0.08710801, 0.03588803, 0.03836535, 0.03424403, 0.03594545, 0.03288215, 0.1376429, 0.188709, 0.1544522, 0.02852949, 0.03100681, 0.04543546, 0.2435373, 0.2656196, 0.03346813, 0.03513096, 0.03966968, 0.04060551)
```

```{r}
numeric_values4 <- c(0.04396976, 0.05169497, 0.03957633, 0.02852949, 0.09637568, 0.08501548, 0.08748784, 0.03243895, 0.05933386, 0.03073753, 0.1109068, 0.2022048, 0.2430773, 0.03428657, 0.05489332, 0.03791541, 0.03853542, 0.03831399, 0.02852949, 0.2233148, 0.1940172, 0.2677522, 0.1019617, 0.08272154, 0.04465793, 0.06785469, 0.1624028, 0.1801293, 0.03261249, 0.03431391, 0.1881379, 0.1732071, 0.05409526, 0.04110811, 0.23389, 0.2307704, 0.1999397, 0.0677184, 0.0389041, 0.08058753, 0.07961798, 0.03346813, 0.04226834, 0.03023091, 0.03015155, 0.09120816, 0.06918694, 0.03073753, 0.1362804, 0.1197119, 0.1241411, 0.03176672, 0.1394714, 0.145925, 0.2644494, 0.2823921, 0.03176672, 0.06974481, 0.1029336, 0.03727721, 0.0581026, 0.0381282, 0.03100681, 0.02911548, 0.1455273, 0.1028649, 0.221001, 0.2646661, 0.2537818, 0.2438705, 0.08140258, 0.04635316, 0.05113717, 0.0514585, 0.06057976, 0.05301621, 0.1568065, 0.1557122, 0.03015155, 0.03611899, 0.04172308, 0.03382812, 0.09413522, 0.08010893, 0.04648652, 0.04385547, 0.03073753, 0.02911548, 0.03073753, 0.04475911, 0.03728588, 0.1274041, 0.06718262, 0.05962119, 0.115466, 0.08927351, 0.03485885, 0.03126009, 0.03243895, 0.03433028, 0.03243895, 0.07995387, 0.1534015, 0.1860995, 0.03100681, 0.03243895, 0.03836535, 0.03790747, 0.03760828, 0.03126009, 0.05875942, 0.05071273, 0.04125481, 0.05018672, 0.0352234, 0.12092, 0.03243895, 0.05245677, 0.05583315, 0.03418662, 0.3032837, 0.3032837, 0.03015155, 0.03441411, 0.2185353, 0.1122288, 0.105147, 0.03441411, 0.03118073, 0.03594545, 0.05097758, 0.04539495, 0.04852728, 0.05815171, 0.0536485, 0.1651653, 0.1268712, 0.03508981, 0.0649244, 0.08793894, 0.0437427, 0.0475157)

```


```{r}
numeric_values6 <- c(
  0.03185296, 0.0508993, 0.05102994, 0.04295814, 0.03365805, 0.03243895, 0.06475789, 0.03432339, 
  0.05573636, 0.07057088, 0.03073753, 0.07065335, 0.07896803, 0.0746923, 0.03185296, 0.03073753, 
  0.03365805, 0.03760828, 0.0633185, 0.06318665, 0.07085882, 0.02682295, 0.08102238, 0.03441411, 
  0.03023091, 0.02852949, 0.03015155, 0.06819685, 0.12819, 0.1096932, 0.06619426, 0.1781443, 
  0.2330501, 0.05573636, 0.08985002, 0.136303, 0.03118073, 0.03262887, 0.03949008, 0.03787491, 
  0.03464377, 0.06869144, 0.04720964, 0.2292562, 0.1957261, 0.02852949, 0.292576, 0.2581111, 
  0.02943395, 0.03288215, 0.03346813, 0.04654407, 0.0535023, 0.09538664, 0.1681687, 0.04654407, 
  0.03940669, 0.03015155, 0.04816605, 0.03015155, 0.04670762, 0.2159145, 0.2613072, 0.04202621, 
  0.03787491, 0.2568007, 0.2882099, 0.0452345, 0.04473745, 0.03126009, 0.1750422, 0.03607363, 
  0.03321485, 0.0544613, 0.05146977, 0.03185296, 0.03185296, 0.03185296, 0.03073753, 0.03418662, 
  0.2988875, 0.2798629, 0.2575183, 0.03073753, 0.03586311, 0.1178527, 0.0858501, 0.05014277, 
  0.04601442, 0.2948753, 0.2695079, 0.1192386, 0.03689229, 0.04323724, 0.07620728, 0.03015155, 
  0.1484511, 0.1528808, 0.1169021, 0.04094317, 0.03365805, 0.1567462, 0.1450515, 0.03015155, 
  0.03015155, 0.03073753, 0.03176672, 0.02955868, 0.0596748, 0.04062286, 0.03940669, 0.02955868, 
  0.131499, 0.03118073, 0.03903084, 0.1068049, 0.06399338, 0.03365805, 0.03015155, 0.05846056, 
  0.06597272, 0.2286946, 0.2296713, 0.02852949, 0.04226834, 0.03185296, 0.03153537, 0.2490276, 
  0.2110562, 0.2447439, 0.0647196, 0.06803792, 0.02852949, 0.03073753, 0.02674647, 0.03057493)

```



```{r}
numeric_values8 <- c(
  0.03015155, 0.1318071, 0.168642, 0.1157419, 0.02852949, 0.03015155, 0.2635929, 0.2608782, 0.3225737, 0.07211447, 
  0.03015155, 0.03656766, 0.1075316, 0.1496199, 0.09309476, 0.1224713, 0.06584128, 0.0458889, 0.07751531, 0.03081689, 
  0.3366838, 0.3237856, 0.3349611, 0.07289527, 0.07542047, 0.1104874, 0.1394599, 0.1717615, 0.08490867, 0.05598569, 
  0.07407774, 0.03433028, 0.05331338, 0.03566382, 0.06527161, 0.1913654, 0.03942532, 0.08287364, 0.2111166, 0.2650264, 
  0.09424328, 0.03642678, 0.07045896, 0.1721156, 0.2723609, 0.2754804, 0.2854489, 0.03185296, 0.02852949, 0.03288215, 
  0.1134788, 0.03666393, 0.03418662, 0.03315743, 0.1255415, 0.3037712, 0.04742412, 0.1603732, 0.07848681, 0.1139372, 
  0.1043645, 0.2562771, 0.2766474, 0.267451, 0.03015155, 0.04029481, 0.03073753, 0.03515406, 0.03073753, 0.03185296, 
  0.03185296, 0.04678724, 0.1741957, 0.1150773, 0.1153968, 0.08231652, 0.08181764, 0.0508828, 0.08681764, 0.09028235, 
  0.03185296, 0.03769452, 0.05963154, 0.1198326, 0.1149997, 0.02852949, 0.04561512, 0.07607654, 0.06480551, 0.1172818, 
  0.03642678, 0.03243895, 0.03856968, 0.06198006, 0.07325447, 0.06228992, 0.08376676, 0.03882071, 0.04299944, 0.03970818, 
  0.04339901, 0.1622175, 0.1005464, 0.09920405, 0.1746327, 0.1773997, 0.179836, 0.1535806, 0.1060354, 0.03563475, 
  0.04012567, 0.04083595, 0.03185296, 0.03073753, 0.03508981, 0.03433028, 0.04602969, 0.08573966, 0.06307273, 0.08195204, 
  0.03015155, 0.05875258, 0.03015155, 0.03015155, 0.03015155, 0.1190013, 0.12844, 0.04585883, 0.03997273, 0.0352234, 
  0.03203599, 0.0389041, 0.03015155, 0.03957633, 0.02852949, 0.05171069, 0.05411742)

```

```{r}
numeric_values9 <- c(
  0.03351579, 0.08458212, 0.04638965, 0.04457396, 0.2948519, 0.2975695, 0.03243895, 0.182159, 0.155164, 0.1181762, 
  0.1060522, 0.03176672, 0.03709901, 0.03015155, 0.0587404, 0.03185296, 0.0667438, 0.04262768, 0.03118073, 0.03073753, 
  0.0387299, 0.2703083, 0.2766783, 0.2628309, 0.04455274, 0.04840386, 0.04468824, 0.04976596, 0.08411597, 0.03535946, 
  0.03185296, 0.04060551, 0.04312228, 0.03594545, 0.03073753, 0.2988343, 0.2941336, 0.2909049, 0.04578389, 0.03521721, 
  0.03015155, 0.03346813, 0.03185296, 0.05108712, 0.04396976, 0.04060551, 0.05610374, 0.03436536, 0.04188401, 0.1148829, 
  0.1390214, 0.06514339, 0.1176715, 0.03243895, 0.1104037, 0.03015155, 0.03903595, 0.03433028, 0.04094317, 0.03015155, 
  0.03185296, 0.1268387, 0.0679592, 0.05604328, 0.2009156, 0.1613777, 0.08055499, 0.04849554, 0.2259848, 0.1055987, 
  0.03185296, 0.03185296, 0.04407194, 0.04152915, 0.02852949, 0.0389041, 0.1608829, 0.03185296, 0.03185296, 0.03346813, 
  0.02955868, 0.185504, 0.2226736, 0.2693507, 0.06355772, 0.03346813, 0.03176672, 0.02852949, 0.02852949, 0.1376201, 
  0.1651953, 0.03073753, 0.03902483, 0.04083442, 0.03243895, 0.06614645, 0.1022676, 0.1163605, 0.06708764, 0.04619363, 
  0.03243895, 0.05708483, 0.04483754, 0.03321485, 0.03118073, 0.03962202, 0.04342282, 0.03418662, 0.05629644, 0.06448093, 
  0.04867312, 0.1666338, 0.1701411, 0.02836853, 0.1286781, 0.03015155, 0.09368846, 0.03329421, 0.1234598, 0.231154, 
  0.2230681, 0.1246253, 0.05007939, 0.03015155, 0.03185296, 0.03535946, 0.04060551, 0.2326934, 0.2429136, 0.03882071, 
  0.09260018, 0.04602737, 0.02674647, 0.02939772, 0.03185296, 0.04536047, 0.03243895)

```

```{r}
numeric_values10 <- c(
  0.03023091, 0.03455117, 0.03185296, 0.03424403, 0.03094939, 0.03243895, 0.03073753, 0.03185296, 
  0.1268046, 0.1903755, 0.03073753, 0.07175252, 0.127252, 0.1481289, 0.03073753, 0.09029524, 
  0.1522828, 0.03015155, 0.03176672, 0.07764473, 0.03262887, 0.02852949, 0.06550109, 0.06171513, 
  0.02733246, 0.03015155, 0.03243895, 0.0712783, 0.0541592, 0.03346813, 0.04052362, 0.03073753, 
  0.04133811, 0.03787491, 0.05435808, 0.032936, 0.03015155, 0.03365805, 0.03015155, 0.03365805, 
  0.03073753, 0.03015155, 0.03015155, 0.04716164, 0.2276509, 0.2149963, 0.228599, 0.03185296, 
  0.03185296, 0.03118073, 0.03015155, 0.2181395, 0.2497938
)

```



```{r}

numeric_values <- c(numeric_values, numeric_values4, numeric_values6, numeric_values8, numeric_values9, numeric_values10)

head(nba_train)
# Create a data frame with a column named 'values'
nba_train$prediction <- data.frame(prediction = numeric_values)

```

```{r}
library(dplyr)

nba_train2 <- nba_train %>%
  group_by(idPlayerTeam, yearSeason.y) %>%
  summarize(sum(prediction),sum(SalaryToCapRatio), sum(Salary))

```

```{r}
nba_test2 <- nba_test %>%
  group_by(idPlayerTeam,yearSeason.y) %>%
  summarize(sum(prediction),sum(SalaryToCapRatio), sum(Salary))
```

```{r}
merged_data <- merge(nba_train2, nba_test2, by = c("idPlayerTeam", "yearSeason.y"), all = TRUE)
merged_data <- merged_data %>%
  replace(is.na(.),0) %>%
  mutate(totalpred = `sum(prediction).x` + `sum(prediction).y`,
         totalsalaryCapRatio = `sum(SalaryToCapRatio).x` + `sum(SalaryToCapRatio).y`) %>%
  mutate(value = totalpred - totalsalaryCapRatio)
```

```{r}
nbateams <- nba_teams(league = "NBA") %>%
  select(idTeam, slugTeam)
```

```{r}
merged_data2 <- merge(merged_data, nbateams, by.x = "idPlayerTeam", by.y = "idTeam", all = FALSE)
merged_data2
```

```{r}
options(scipen = 999)
ggplot(merged_data2, aes(x=value, y=totalsalaryCapRatio, color=factor(yearSeason.y), label=slugTeam)) +
  geom_point() + # Add points
  geom_text(hjust=0.5, vjust=-1) + # Add team labels
  labs(x='Total Value', y='Total Salary', color='Year Season') + # Label axes and color legend
  theme_minimal() 
```

